version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainee-football-app
    env_file: .env
    working_dir: /src
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: $DATABASE_URL
      NODE_ENV: $NODE_ENV
      PORT: $PORT
      POSTGRES_HOST_PORT: $POSTGRES_HOST_PORT
      POSTGRES_CONTAINER_PORT: $POSTGRES_CONTAINER_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /data/mydatabase
    volumes:
      - pgstore:/var/lib/postgresql/data
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgstore:
  pgadmin:
