version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trainee-football-app-transfer-db
    ports:
      - "5433:5432"
    volumes:
      - trainee_football_app_transfer_db:/var/lib/postgresql/data
    networks:
      - trainee_football_app_transfer_network

volumes:
  trainee_football_app_transfer_db:
    driver: local

networks:
  trainee_football_app_transfer_network:
    driver: bridge