CREATE SCHEMA IF NOT EXISTS football;

CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);