version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=football
    ports:
      - "5432:5432"
    volumes:
      - football_db:/var/lib/postgresql/data
    networks:
      - football_network

volumes:
  football_db:
    driver: local

networks:
  football_network:
    driver: bridge