version: '3.8'

services:
  registration-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registration-service
    env_file: .env
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: $DATABASE_URL
      NODE_ENV: $NODE_ENV
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - "${POSTGRES_PORT}:5432"